---
- block:
    - name: Add passwordless sudo access for kube-spray user
      lineinfile:
        dest: /etc/sudoers
        line: 'kube-spray ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        state: present

