---
- name: Install Python and Pip on Red Hat Linux
  hosts: [node1]
  become: yes
  tasks:
    - name: Install Python
      package:
        name: python3
        state: present

    - name: Install Pip
      package:
        name: python3-pip
        state: present