---
- name: create ssh key and transfer it to all nodes
  hosts: all
  remote_user: kube-spray  # Update this to the appropriate user for your setup
  become: yes
  tasks:
    - name: Generate SSH key
      ansible.builtin.command: ssh-keygen -t rsa -b 2048 -f /home/kube-spray/.ssh/id_rsa -N ""
      args:
        creates: /home/kube-spray/.ssh/id_rsa
      ignore_errors: yes

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/kube-spray/.ssh
        state: directory
        mode: '0700'
        owner: kube-spray
        group: kube-spray

    - name: Set up authorized keys with password authentication
      ansible.builtin.copy:
        content: "{{ lookup('file', '/home/kube-spray/.ssh/id_rsa.pub') }}"
        dest: /home/kube-spray/.ssh/authorized_keys
        mode: '0600'
        owner: kube-spray
        group: kube-spray
      delegate_to: "{{ inventory_hostname }}"
      when: inventory_hostname != ansible_hostname

    - name: Ensure correct permissions on the SSH key
      ansible.builtin.file:
        path: /home/kube-spray/.ssh/id_rsa
        mode: '0600'
        owner: kube-spray
        group: kube-spray

    - name: Ensure correct permissions on the SSH public key
      ansible.builtin.file:
        path: /home/kube-spray/.ssh/id_rsa.pub
        mode: '0644'
        owner: kube-spray
        group: kube-spray

    - name: Set up authorized keys with password authentication for worker1
      ansible.builtin.copy:
        content: "{{ lookup('file', '/home/kube-spray/.ssh/id_rsa.pub') }}"
        dest: /home/worker1/.ssh/authorized_keys
        mode: '0600'
        owner: worker1
        group: worker1
      delegate_to: "{{ inventory_hostname }}"
      when: inventory_hostname == 'worker1'

    - name: Set up authorized keys with password authentication for worker2
      ansible.builtin.copy:
        content: "{{ lookup('file', '/home/kube-spray/.ssh/id_rsa.pub') }}"
        dest: /home/worker2/.ssh/authorized_keys
        mode: '0600'
        owner: worker2
        group: worker2
      delegate_to: "{{ inventory_hostname }}"
      when: inventory_hostname == 'worker2'
