---
- block:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/kube-spray/.ssh
        state: directory
        mode: '0700'
        owner: kube-spray
        group: kube-spray

    - name: Generate SSH key
      ansible.builtin.command: ssh-keygen -t rsa -b 2048 -f /home/kube-spray/.ssh/id_rsa -N ""
      args:
        creates: /home/kube-spray/.ssh/id_rsa
      ignore_errors: true

    - name: Ensure correct permissions on the SSH key
      ansible.builtin.file:
        path: /home/kube-spray/.ssh/id_rsa
        mode: '0600'
        owner: kube-spray
        group: kube-spray

    - name: Ensure correct permissions on the SSH public key
      ansible.builtin.file:
        path: /home/kube-spray/.ssh/id_rsa.pub
        mode: '0644'
        owner: kube-spray
        group: kube-spray

    - name: Include task to read public key
      include_tasks: read_public_key.yml

    - name: Add SSH public key to authorized_keys
      ansible.builtin.lineinfile:
        path: /home/kube-spray/.ssh/authorized_keys
        line: "{{ public_key['content'] | b64decode }}"
        create: yes
        mode: '0600'
        owner: kube-spray
        group: kube-spray